### ISSUE TITLE
dir with figure is deleted in multi format generation

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1503]
From a question on [Rstudio community](https://community.rstudio.com/t/rmarkown-pdf-document-removes-other-files/20289/3), it seems that default behaviour for `html_document` is to delete the whole `files_dir` of the form `*_files` even if something else from other format is there.

I tried to come up with a reprex for this. See below

* `github_document` generate a figure that lives in a `figure-gfm` folder, required to use with the md file generated 
* `html_document` by default is `self_contained=TRUE`, so cleaning is activated (unless `clean = FALSE` in `render`. The cleaning process suppress the **whole** `files_dir` , *including the `figure-gfm`
* using output format `"all"` to generate both format shows that everything is deleted and the png file for the plot does not exist anymore for the github_document format.

````r
# create temporary directory to work in for example
dir_temp <- fs::path_temp("rmd")
fs::dir_create(dir_temp)

# create test rmd file
test_rmd <- fs::file_temp("test", dir_temp, ext = ".Rmd")
writeLines(c('---
title: "R Notebook"
output:
  github_document: default
  html_document:
      self_contained: true
---',
'This is a test file

```{r cars-plot, fig.cap = "plot of cars"}
plot(cars)
```

```{r mean-speed}
mean_speed <- mean(cars$speed)
```
'), test_rmd)

fs::dir_ls(dir_temp)
# creating plot file in a new folder
rmarkdown::render(test_rmd, "github_document")
fs::dir_ls(dir_temp, regexp = "_files", recursive = TRUE)

# without clean the dir is here
rmarkdown::render(test_rmd, "html_document", clean = FALSE)
fs::dir_ls(dir_temp, regexp = "_files", recursive = TRUE)

# with default clean = TRUE, the whole dir is deleted, even the file from github_document format.
rmarkdown::render(test_rmd, "html_document")
fs::dir_ls(dir_temp, regexp = "_files", recursive = TRUE)
fs::dir_ls(dir_temp, recursive = TRUE)

# no folder for github document containing the image
rmarkdown::render(test_rmd, "all")
fs::dir_ls(dir_temp, regexp = "_files", recursive = TRUE)
fs::dir_ls(dir_temp, recursive = TRUE)

# both folder are present
rmarkdown::render(test_rmd, "all", clean = FALSE)
fs::dir_ls(dir_temp, regexp = "_files", recursive = TRUE)
fs::dir_ls(dir_temp, recursive = TRUE)

# clean
unlink(dir_temp, recursive = TRUE)
````

There are different argument fir a workaround (`clean = FALSE`, or `self_contained: false`, change fig_path location) that will prevent that, but seems like an non wanted effect. 

What do you think ?

**Comment by yihui** [comment]
Duplicate of #1472

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report and the reprex!

**Comment by cderv** [comment]
It seems like this is not fixed. I rerun the reprex and the issue still here. I see where it comes from. 
I can help with a PR if you want.
