### ISSUE TITLE
knit_meta_id grows out of control when kableExtra is loaded

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#1538]
Not sure if this is a bug in `kableExtra` or `rmarkdown`, but reporting here for posterity.

``` r

library(kableExtra)
str(attr(knitr:::.knitEnv$meta, "knit_meta_id"))
#>  chr [1:14] "" "" "" "" "" "" "" "" "" "" "" "" "" ""
file <- tempfile(fileext = ".Rmd")
file.create(file)
#> [1] TRUE
rmarkdown::render(file, output_format = "html_notebook")
#> /usr/local/bin/pandoc +RTS -K512m -RTS file14f2f24ec1abe.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output file14f2f24ec1abe.html --email-obfuscation none --self-contained --standalone --section-divs --template /Users/kevin/Library/R/3.5/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T//Rtmp231SWc/rmarkdown-str14f2f8cfc2e2.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --metadata pagetitle=file14f2f24ec1abe.utf8.md --variable code_folding=show --variable source_embed=file14f2f24ec1abe.Rmd --include-after-body /var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T//Rtmp231SWc/file14f2f387f3.html --variable code_menu=1 --variable kable-scroll=1
#> 
#> Output created: file14f2f24ec1abe.nb.html
str(attr(knitr:::.knitEnv$meta, "knit_meta_id"))
#>  chr [1:196] "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ...
rmarkdown::render(file, output_format = "html_notebook")
#> /usr/local/bin/pandoc +RTS -K512m -RTS file14f2f24ec1abe.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output file14f2f24ec1abe.html --email-obfuscation none --self-contained --standalone --section-divs --template /Users/kevin/Library/R/3.5/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T//Rtmp231SWc/rmarkdown-str14f2f67d26286.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --metadata pagetitle=file14f2f24ec1abe.utf8.md --variable code_folding=show --variable source_embed=file14f2f24ec1abe.Rmd --include-after-body /var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T//Rtmp231SWc/file14f2f254280aa.html --variable code_menu=1 --variable kable-scroll=1
#> 
#> Output created: file14f2f24ec1abe.nb.html
str(attr(knitr:::.knitEnv$meta, "knit_meta_id"))
#>  chr [1:2744] "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ...
```

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 3.5.2 Patched (2019-01-14 r75994)
#>  os       macOS Mojave 10.14.3                       
#>  system   x86_64, darwin15.6.0                       
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_US.UTF-8                                
#>  ctype    en_US.UTF-8                                
#>  tz       America/Los_Angeles                        
#>  date     2019-02-27                                 
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                        
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)                
#>  base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)                
#>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                
#>  colorspace    1.4-0      2019-01-13 [1] standard (@1.4-0)             
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                
#>  devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.2)                
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                
#>  evaluate      0.13       2019-02-12 [1] CRAN (R 3.5.2)                
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                
#>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                
#>  highr         0.7        2018-06-09 [1] standard (@0.7)               
#>  hms           0.4.2      2018-03-10 [1] CRAN (R 3.5.0)                
#>  htmltools     0.3.6      2017-04-28 [1] standard (@0.3.6)             
#>  httr          1.4.0      2018-12-11 [1] CRAN (R 3.5.0)                
#>  kableExtra  * 1.0.1      2019-01-22 [1] CRAN (R 3.5.2)                
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.5.2)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                
#>  munsell       0.5.0      2018-06-12 [1] standard (@0.5.0)             
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.0)                
#>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.0)                
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.0)                
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)                
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)                
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                
#>  Rcpp          1.0.0.1    2019-02-12 [1] local                         
#>  readr         1.3.1      2018-12-21 [1] standard (@1.3.1)             
#>  remotes       2.0.2.9000 2019-01-22 [1] Github (r-lib/remotes@8397195)
#>  rlang         0.3.1      2019-01-08 [1] CRAN (R 3.5.2)                
#>  rmarkdown     1.11       2018-12-08 [1] standard (@1.11)              
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                
#>  rstudioapi    0.9.0      2019-01-22 [1] local                         
#>  rvest         0.3.2      2016-06-17 [1] standard (@0.3.2)             
#>  scales        1.0.0      2018-08-09 [1] standard (@1.0.0)             
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                
#>  stringi       1.3.1      2019-02-13 [1] CRAN (R 3.5.2)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                
#>  testthat      2.0.1      2018-10-13 [1] standard (@2.0.1)             
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                
#>  usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.0)                
#>  viridisLite   0.3.0      2018-02-01 [1] standard (@0.3.0)             
#>  webshot       0.5.1      2018-09-28 [1] CRAN (R 3.5.0)                
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                
#>  xfun          0.5        2019-02-20 [1] CRAN (R 3.5.2)                
#>  xml2          1.2.0      2018-01-24 [1] CRAN (R 3.5.0)                
#>  yaml          2.2.0      2018-07-25 [1] standard (@2.2.0)             
#> 
#> [1] /Users/kevin/Library/R/3.5/library
#> [2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

Note that the `knit_meta_id` attribute grows in size each time `render()` is called. If called enough times, the session will be exhausted of memory. See https://github.com/rstudio/rstudio/issues/2340 for a case where this happens in the wild -- e.g. in R Notebooks, we do call `render()` behind the scenes multiple times in a single session.

The main things to note about this bug:

1. Loading the `kableExtra` package modifies the `.knitEnv$meta` object;
2. Calling `rmarkdown::render()` causes that object to explode in size, presumedly from here: https://github.com/rstudio/rmarkdown/blob/bbd0786d82f82d9eaef7f0b9e2c553b523407161/R/render.R#L416-L423

I'm not sure if the issue here is that `kableExtra` is doing something it shouldn't, or if `rmarkdown` is not correctly saving / restoring the knit meta object.

**Comment by CrashVector** [comment]
Yes!! I've been fighting this for the last few days trying to figure out what is going on!  I have a server with 192GB of ram, and after the third time or so of running a render to pdf using kableExtra, my rsession grinds to a halt utilizing ALL available ram.  I have to bring the server down in order to clear the session. I have been trying to troubleshoot this, and it seems like the more kable tables I have in my template, the quicker this happens.  Does that make sense in terms of the underlying bug?

**Comment by nikkoc** [comment]
What's interesting is that I can recreate this bug using the code above, but as soon as I call `knitr::knit_meta()`, the problem goes away for each additional render and I have to restart in order to start getting the bug again. 

It looks like `kableExtra` adds to the `knitr:::.knitEnv$meta` every time `kableExtra::usepackage_latex` is called, which [appears to be default on load](https://github.com/haozhu233/kableExtra/blob/f1873a4f7a5648b38c6717960eb6378670831416/R/zzz.R#L3-L18). This seems to be why we get a vector of 14 empty strings for `attr(knitr:::.knitEnv$meta, "knit_meta_id")`. 

But having an initial value shouldn't cause the value to get LARGER for each additional render. Given the code in `rmarkdown::render` at lines 416:423 referenced above, it should just stay as a vector of 14 empty strings. Except it isn't, so I think this is a bug in `rmarkdown::render()`. 

It seems like a quick workaround is to just call `knitr::knit_meta()` after loading kableExtra (or to be safe, before calling `rmarkdown::render()`) to make sure that the knit_meta is clear before calling the `render` function.

**Comment by CrashVector** [comment]
It's overkill, but i;ve added `invisible(knitr::knit_meta(clean=T))` before i call my renderin my main script, then I added `knitr::knit_meta()` after loading kableExtra in my markdown, and then `invisible(gc())` after the render call in my main script.

BUT, i no longer have the runaway memory issue!  My server takes 35 minutes to boot (a problem for another day), so I am so happy to have a workaround for this!

**Comment by nikkoc** [comment]
It looks like `attr(knitr:::.knitEnv$meta, "knit_meta_id")` size is multiplying by the length of `old_knit_meta` inside `knitr::knit_meta_add()`. The `knit_meta_add` function is as follows:

`function (meta, label = "") `
`{`
`  if (length(meta)) {`
`    meta_id = attr(.knitEnv$meta, "knit_meta_id")`
 `   .knitEnv$meta = c(.knitEnv$meta, meta)`
 `   attr(.knitEnv$meta, "knit_meta_id") = c(meta_id, rep(label,  length(meta)))`
  `}`
`  .knitEnv$meta`
`}`

So we can see that it reps the label param for the length of the meta param as though it assumes the length of label is 1. However, `render` is passing the entire vector, so we repeat the entire vector for the length of the meta param. If we load kableExtra, that immediately makes the meta length 14 and the label length 14, so after the first iteration, the `knit_meta_id` attribute is now `14*14=`196 strings long. Assuming the length of meta hasn't changed, the second iteration would now be `196*14=`2,744 strings long. And so on and so forth.

It looks like this chunk of code in `rmarkdown::render()` was added in PR #1153 . Since I'm not familiar with how knitr metadata works, I don't know if the solution would be to change `knitr::knit_meta_add()` to somehow accept a vector or to change `rmarkdown::render()` to only pass through a vector of length = 1. I'm leaning towards the former, but really I have no clue.

**Comment by yihui** [comment]
@nikkoc Thanks for investigating the issue and pointing out the root cause! You were absolutely correct, and I have fixed it in **knitr**. You may install the development version via

```r
remotes::install_github('yihui/knitr')
```

**Comment by haozhu233** [comment]
I also improved this on the `kableExtra` side in the new version so those latex packages are only loaded when `knitr::is_latex_output()` == TRUE

https://github.com/haozhu233/kableExtra/blob/e69a890301f8c13047f4bc3453f944de7211be5f/R/zzz.R#L2-L20

**Comment by Kreitzberg** [comment]
I believe I am still having this issue. I was able to knit an Rstudio notebook until I added kable tables with kableExtra and now I'm running out of memory. I'm not sure how I should go about making sure that this is the issue. I installed the dev version of knitr and its still happening.

Any help would be awesome.

**Comment by kevinushey** [comment]
@Kreitzberg you are most likely seeing a separate issue -- I cannot reproduce the original problem I reported with the development version of knitr.

If you can, I would recommend filing a new issue with a reproducible example. (If you cannot create a reproducible example, it is unlikely that your problem will be fixed.)

**Comment by Kreitzberg** [comment]
Oh I see, when I try to knit my notebook it goes until it says the name of the output file after the last chunk and then gives me the pandoc memory failure error. I enabled more memory usage by pandoc.exe. However, I'm not sure how to check pandoc logs to see where it fails. 

Do you have any resources for how to figure out why pandoc memory is failing? I'm 99% it has something to do with kable/kableExtra. I'm just not sure how to figure out exactly why its failing.

**Comment by Kreitzberg** [comment]
Nevermind, I realized I forgot to use head() and was printing large tables! Thanks for your help.
