### ISSUE TITLE
rmarkdown creates _files directory not cleared

### ISSUE THREAD

**Issue by wxli0** [rstudio/rmarkdown#1553]
Hello,

I was playing with rmarkdown::render() function. After that, I found knit in rmarkdown always created an empty "_files" directory, which I do not want. Is there any commands that can help me get rid of this directory automatically? I have attached the all the render commands I have tried.

```library(rmarkdown)
# output_dir <- "result"
# render()
# rmarkdown::render("6_1p_CSC05a_onset.Rmd", output_file = "result/6_1p_CSC05a_onset.pdf")
# rmarkdown::render('6_1p_CSC05a_onset.Rmd', 
#                   output_file='6_1p_CSC05a_onset.md')
# rmarkdown::render("6_1p_CSC05a_onset.Rmd")
# knit("doc.Rmd", "papers/doc.md")
# knit("6_1p_CSC05a_onset.Rmd", "result/6_1p_CSC05a_onset.md")
# opts_knit$set(output.dir="result")
# must place in the folder as iRaster.R due to source(...)
# rmarkdown::render("6_1p_CSC05a_onset.Rmd", output_format = "all",  clean = TRUE)
```

In my case, it always created 6_1p_CSC05a_onset_files folder in the same folder as 6_1p_CSC05a_onset.pdf. Any help would be appreciated!

**Comment by wxli0** [comment]
Is there any update on this issue?

**Comment by olyerickson** [comment]
It is normal for Markdown to create the empty "_files" directory, but it usually cleans up after itself. We sometimes see it left behind when a knit fails; for example, when our students attempt to knit an Rmd with Plotly figures to PDF. 

Side note: These left-behind "_files" directories can be a real PITA in a collaborative, multi-user environment, since they usually are set with write access only for the user who generated them (RStudio Server doesn't set write for the group). This is not a "bug" per se, since RStudio Server is basically doing the right thing from a security standpoint...

**Comment by wxli0** [comment]
The "_files" directory is not cleaned up after knit and knit does not fail (i.e. the pdf has been generated successfully). Is there any command to force Rstudio to clean it up?

**Comment by yihui** [comment]
Should be fixed now with @cderv's PR #1566. Thanks everyone!

**Comment by dchiu911** [comment]
The fix isn't passed on to `rmarkdown::render_site()`, hence I am still getting the directory `_bookdown_files/.../figure-html/...` generated

**Comment by cderv** [comment]
Can you open a new issue with a reproductible example on how it worked before and how it works now ? 
I tested it with current issues and it works as I believe was expected
I need to see how it works with rmardown website. Or maybe bookdown here I guess ? 
Also Not all rmardown format are cleanable format. A website has generally its ressources available as files and linked in the html.

**Comment by yihui** [comment]
@dchiu911 Judging from the directory name `_bookdown_files`, it seems you were using **bookdown**. If that is the case, `_bookdown_files` won't be automatically removed. This is by design, because **bookdown** pages are usually not self-contained. As @cderv said, we need more information from you to know whether it is a bug or not.

**Comment by wxli0** [comment]
Thanks very much.
Is updating "rmarkdown" package the only change I need to make to get rid of the _files directory?

**Comment by yihui** [comment]
Yes, you can install the development version via

```r
remotes::install_github('rstudio/rmarkdown')
```
