### ISSUE TITLE
bibliography with Rmd on shiny server

### ISSUE THREAD

**Issue by thomasbrand** [rstudio/rmarkdown#430]
When I put in a folder on my shiny server an Rmd file with metadata
```
---
output: html_document
bibliography: biblio.bib
---
```
I have the following error :
```
pandoc-citeproc: user error (Not found: biblio.bib)
pandoc: Error running filter /usr/lib/rstudio/bin/pandoc/pandoc-citeproc
Error : pandoc document conversion failed with error 83
```
However, when I run the code in RStudio, it works fine. I think it is related to #290.

**Comment by jjallaire** [comment]
I think we may have fixed this version in the recent rmarkdown update (v0.6.1, now on CRAN). @jmcphers Do you expect that this should be resolved by the recent work we did?

**Comment by thomasbrand** [comment]
I am sorry I still have the same problem with the version 0.6.1 of rmarkdown.

**Comment by thomasbrand** [comment]
Sorry to insist, but even locally when I omit 'runtime: shiny' it works great, but not when I add it. Even with the rmarkdown version on github (master branch). Thanks again.

**Comment by aronatkins** [comment]
Here is how to reproduce the issue independent of Shiny Server.
```
rmarkdown::run(file="bib.Rmd")
```
Underneath `rmarkdown::run`, we use `intermediates_dir` as an argument when rendering. It is likely that we are not copying rendering resources into the proper intermediate location when running with shiny.

**Comment by aronatkins** [comment]
Fixed with #442.

**Comment by thomasbrand** [comment]
Great, it works perfectly, thanks a lot!
