### ISSUE TITLE
Order of filters in pandoc invocation

### ISSUE THREAD

**Issue by lierdakil** [rstudio/rmarkdown#592]
Hi.

I'm an author of [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) filter, and apparently using this filter with RMarkdown can be challenging (judging from user reports)

From skimming over sources in this repository, I found that custom Pandoc arguments are passed after `--filter pandoc-citeproc`. This invariably breaks filters that leverage citation syntax for other purposes (like pandoc-crossref does), due to `pandoc-crossref` being applied before other filters.

Solution would be to move `--filter pandoc-crossref` to the end of argument list, or at least somewhere after custom Pandoc arguments.

Thanks.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/07da2572770568234b89ee2951a0b592f46e490f

@yihui This commit moves the pandoc-citeproc filter to be the very last thing passed to pandoc (this is so that other filters can make use of pandoc citation syntax). I know you've recently done some work related to citeproc, is there anything you can think of in this change that might cause breakage elsewhere?

**Comment by yihui** [comment]
That looks good to me.

**Comment by HJAllen** [comment]
I am one of the users Lierdakil is referring to.  I have updated rmarkdown to 0.9.5 and the command is as follows:
```
"C:/path/cabal/bin/pandoc" +RTS -K512m -RTS HABsLitReview.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output HABsLitReview.pdf --template "c:\path\R\library\rmarkdown\rmd\latex\default-1.15.2.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "..\\HABsPDFheader.tex" --variable graphics=yes --filter pandoc-crossref --bibliography "..\\HABs.bib" --filter pandoc-citeproc 
```
but the crossref still fails.  if I remove the extensions it works from the command line as in:
```
"C:/path/cabal/bin/pandoc" +RTS -K512m -RTS HABsLitReview.utf8.md --to latex --from markdown --output HABsLitReview.pdf --template "c:\path\R\library\rmarkdown\rmd\latex\default-1.15.2.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "..\\HABsPDFheader.tex" --variable graphics=yes --filter pandoc-crossref --bibliography "..\\HABs.bib" --filter pandoc-citeproc 
````
is it possible to option the extensions as well?
thanks.

**Comment by lierdakil** [comment]
Oh. Right. It's because `-implicit-figures` (crossref relies on that one).

**Comment by lierdakil** [comment]
@HJAllen, I think you can add those back using `extensions` field?

**Comment by lierdakil** [comment]
Something along the lines of
```
output: 
      pdf_document:
	    md_extensions: implicit_figures
```
from what I gather from sources at a glance, maybe?

**Comment by jjallaire** [comment]
Yes, you should be able to specify:

md_extensions: "+implicit-figures"

To get those extensions re-enabled.

**Comment by jjallaire** [comment]
That's right , you just need the "+" as well to indicated adding it back in.

**Comment by yihui** [comment]
I'd set the `fig_caption` option to `TRUE` (it is `FALSE` by default):

```r
output: 
    pdf_document:
        fig_caption: yes
```

**Comment by HJAllen** [comment]
All is well now with '+implicit_figures"
Thanks for the help on this topic and thanks for all the work you all have put in to make a great tool!

**Comment by jjallaire** [comment]
I think that Yihui's suggestion of using fig_caption = TRUE will also
automatically add the +implicit_figures.

**Comment by HJAllen** [comment]
thanks for the clarification.  I added fig_caption: yes and saw no obvious change in the output.

**Comment by jjallaire** [comment]
Okay, perhaps I'm wrong about that!

**Comment by yihui** [comment]
@HJAllen `implicit_figures` is the default extension, so unless you exclude it, it should be there automatically. `fig_caption = FALSE` means rmarkdown will add `-implicit_figures`, and `TRUE` means it will not. If `TRUE` does not work, it is probably a bug, and we need a reproducible example.

**Comment by HJAllen** [comment]
works as described.  I was not clear earlier.  I had both 
```
    md_extensions: "+implicit_figures"
    fig_caption: yes
```
in the yaml header and saw no difference as they are redundant.

**Comment by crsh** [comment]
Hi, I'm trying to apply a filter *after*  `--filter pandoc-citeproc` because it makes a slight modification to the citations (jgm/pandoc-citeproc#177). Is this somehow possible?

**Comment by faridcher** [comment]
Hi,

to enable pandoc-crossref filter I have added the following line to  my yaml:

```yaml
pdf_document:
extensions: +implicit_figure
pandoc_args: [
          --filter pandoc-crossref
        ]
```
The final command that knitr creates is:

> "C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS rmd.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+implicit_figures+emoji --output pandoc15c323d16a9.tex --table-of-contents --toc-depth 3 --template "C:\Users\Farid\Documents\R\win-library\3.3\rmarkdown\rmd\latex\default-1.17.0.2.tex" --number-sections --highlight-style tango --latex-engine pdflatex --variable graphics=yes "--filter pandoc-crossref" --variable "geometry:margin=1in" --bibliography bib1.bib --filter pandoc-citeproc

It quotes the whole filter argument and throws this error:
> pandoc: unrecognized option `--filter pandoc-crossref' Try pandoc --help for more information.

If I remove the double quotes by hand, it works fine.
How could we avoid this?

**Comment by lierdakil** [comment]
Try

```yaml
pdf_document:
    extensions: +implicit_figure
    pandoc_args: [
           --filter, pandoc-crossref
        ]
```
? Those should be two distinct arguments instead of one.

**Comment by faridcher** [comment]
@lierdakil , I just found out. Thanks anyway.
